/**
 * Role labels for performers and contributors
 * These labels are always displayed in English, regardless of the interface language
 */

export const ROLE_LABELS = {
  // Performer roles
  main_performer: "Main Performer",
  featuring: "Featuring",
  remixer: "Remixer",
  
  // Core contributor roles
  composer: "Composer",
  lyricist: "Lyricist",
  arranger: "Arranger",
  mixing_engineer: "Mixing Engineer",
  mastering_engineer: "Mastering Engineer",
  cover_designer: "Cover Designer",
  producer: "Producer",
  
  // Additional roles
  background_vocal: "Background Vocal",
  musician: "Musician",
  additional_engineer: "Additional Engineer",
  additional_producer: "Additional Producer",
  art_production: "Art Production",
  assistant_editing_engineer: "Assistant Editing Engineer",
  assistant_engineer: "Assistant Engineer",
  assistant_recording_engineer: "Assistant Recording Engineer",
  assistant_strings_engineer: "Assistant Strings Engineer",
  associate_producer: "Associate Producer",
  audio_processing: "Audio Processing",
  audio_restoration: "Audio Restoration",
  audio_technician: "Audio Technician",
  balance_engineer: "Balance Engineer",
  bass_technician: "Bass Technician",
  camera_operator: "Camera Operator",
  choreography: "Choreography",
  cinematography: "Cinematography",
  co_producer: "Co-Producer",
  compilation_producer: "Compilation Producer",
  computer_graphics: "Computer Graphics",
  concert_producer: "Concert Producer",
  costume_design: "Costume Design",
  cover_art: "Cover Art",
  cover_photography: "Cover Photography",
  creative_director: "Creative Director",
  drawing: "Drawing",
  drum_technician: "Drum Technician",
  editing_engineer: "Editing Engineer",
  engineer: "Engineer",
  engraving: "Engraving",
  equipment_technician: "Equipment Technician",
  film_director: "Film Director",
  film_editor: "Film Editor",
  film_producer: "Film Producer",
  graphic_design: "Graphic Design",
  guitar_technician: "Guitar Technician",
  harpsichord_technician: "Harpsichord Technician",
  harpsichord_tuner: "Harpsichord Tuner",
  illustrator: "Illustrator",
  keyboard_technician: "Keyboard Technician",
  lighting_design: "Lighting Design",
  lithography: "Lithography",
  live_mixing_engineer: "Live Mixing Engineer",
  live_production: "Live Production",
  live_recording_engineer: "Live Recording Engineer",
  music_supervisor: "Music Supervisor",
  organ_technician: "Organ Technician",
  original_engineering: "Original Engineering",
  original_producer: "Original Producer",
  other_pe: "Other P&E",
  package_design: "Package Design",
  paintings: "Paintings",
  photo_editor: "Photo Editor",
  photography: "Photography",
  piano_technician: "Piano Technician",
  piano_tuner: "Piano Tuner",
  portraits: "Portraits",
  post_production_assistant: "Post Production Assistant",
  post_production_director: "Post Production Director",
  post_production_editor: "Post Production Editor",
  post_production_engineer: "Post Production Engineer",
  post_production_mixing_engineer: "Post Production Mixing Engineer",
  post_production_supervisor: "Post Production Supervisor",
  recording_engineer: "Recording Engineer",
  recording_supervisor: "Recording Supervisor",
  recording_technician: "Recording Technician",
  reissue_producer: "Reissue Producer",
  remix_producer: "Remix Producer",
  research: "Research",
  score_producer: "Score Producer",
  set_designer: "Set Designer",
  sound_design: "Sound Design",
  soundtrack_producer: "Soundtrack Producer",
  spatial_audio_engineer: "Spatial Audio Engineer",
  spatial_mastering_engineer: "Spatial Mastering Engineer",
  spatial_mixing_engineer: "Spatial Mixing Engineer",
  special_effects: "Special Effects",
  stage_director: "Stage Director",
  stage_manager: "Stage Manager",
  stage_technician: "Stage Technician",
  strings_engineer: "Strings Engineer",
  studio_personnel: "Studio Personnel",
  studio_technician: "Studio Technician",
  stylist: "Stylist",
  tape_editor: "Tape Editor",
  tape_operator: "Tape Operator",
  tape_preparation: "Tape Preparation",
  transfer_engineer: "Transfer Engineer",
  typesetting: "Typesetting",
  typography: "Typography",
  video_director: "Video Director",
  video_editor: "Video Editor",
  video_production: "Video Production",
  videographer: "Videographer",
  vocalist: "Vocalist",
  vocal_mixing_engineer: "Vocal Mixing Engineer",
  vocal_recording_engineer: "Vocal Recording Engineer",
  wardrobe: "Wardrobe",
} as const;

export type RoleKey = keyof typeof ROLE_LABELS;
